"""empty message

Revision ID: 7cecf35a7e2b
Revises: ea3c9e24794b
Create Date: 2021-01-03 16:38:43.800804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cecf35a7e2b'
down_revision = 'ea3c9e24794b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('day', sa.String(length=64), nullable=True))
    op.add_column('activity', sa.Column('time', sa.String(length=64), nullable=True))
    op.add_column('activity', sa.Column('week', sa.String(length=64), nullable=True))
    op.drop_column('activity', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('date_time', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('activity', 'week')
    op.drop_column('activity', 'time')
    op.drop_column('activity', 'day')
    # ### end Alembic commands ###
